services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"   # Exposing the correct Vite port
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:4000  # Update to backend service name
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb+srv://i211195:Fast2021@cluster0.kixwl8x.mongodb.net/Mlops_classtask3?retryWrites=true&w=majority
      - PORT=4000
